# Generated by Django 4.0.4 on 2022-09-21 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_delete_profile_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 0), ('FEMALE', 1), ('OTHER', 2)], max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(blank=True, choices=[('REGISTERED', 0), ('NOTREGISTERED', 1)], max_length=255),
        ),
    ]
