# Generated by Django 4.0.4 on 2022-10-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
