# Generated by Django 4.0.4 on 2022-06-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_manufacturer_product_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
