# Generated by Django 4.0.4 on 2022-10-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(editable=False, max_length=120, unique=True),
        ),
    ]
