# Generated by Django 4.0.4 on 2022-06-12 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_manufacturer_id_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 12, 9, 27, 857720)),
        ),
    ]
