# Generated by Django 4.0.4 on 2022-10-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=10)),
                ('status', models.CharField(blank=True, choices=[('CANCELED', 0), ('WAITING', 1), ('PAYMENT_WAITING', 2), ('APPROVED', 3), ('PREPARING', 4), ('ONSHIPPING', 5), ('SHIPPED', 6), ('DELIVERED', 7), ('REFUNDED', 8)], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('shipped_date', models.DateTimeField(auto_now=True, null=True)),
                ('delivered_date', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
