# Generated by Django 4.0.4 on 2022-10-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem')),
            ],
        ),
    ]
