# Generated by Django 4.0.4 on 2022-10-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderOrderItem',
        ),
    ]
